[package]
name = "ultimattt"
version = "0.1.0"
authors = ["Nelson Elhage <nelhage@nelhage.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
rand = "0.7.2"

[dependencies.smallvec]
version = "1.2.0"
features = ["union"]

[dependencies.structopt]
version = "0.3.11"

[profile.release]
debug = true
